2025-01-04 15:39:41,439 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\1\PycharmProjects\Project2\Tests_12_4.py", line 68, in test_run
    runner_2 = Runner(5, 10)
               ^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\Project2\Tests_12_4.py", line 12, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-04 15:39:41,439 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\1\PycharmProjects\Project2\Tests_12_4.py", line 59, in test_walk
    runner = Runner('Mike', -5)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\Project2\Tests_12_4.py", line 17, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
